name: Test all toolchains

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  create:
    name: Create and test Conan recipes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Conan
        run: |
          python -m pip install --upgrade pip
          pip install "conan>=2.2,<3" PyYAML

      - name: Cache local Conan repo
        uses: actions/cache@v3
        with:
          path: ~/.conan2/p
          key: ${{ runner.os }}-conan2-${{ hashFiles('recipes/**') }}
          restore-keys: |
            ${{ runner.os }}-conan2-

      - name: Build and test recipes
        run: |
          python .github/scripts/build_all_recipes.py
